package com.playtogether.pes.openapi;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;
import org.springframework.test.web.servlet.MockMvc;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * springdoc 자동생성 OpenAPI 문서 검증.
 */
@SpringBootTest
@AutoConfigureMockMvc
class OpenApiDocIntegrationTest {

    @Autowired
    private MockMvc mockMvc;

    @Test
    void apiDocs_areAutoGenerated_fromControllers() throws Exception {
        this.mockMvc.perform(get("/v3/api-docs"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.openapi").exists())
                .andExpect(jsonPath("$.info.title").value("PES (Project Execution System) API"))
                .andExpect(jsonPath("$.info.version").value("0.0.1"))
                // 컨트롤러에서 자동 추출된 경로/오퍼레이션
                .andExpect(jsonPath("$.paths['/lot'].post").exists())
                .andExpect(jsonPath("$.paths['/lot/{lotId}'].get").exists())
                .andExpect(jsonPath("$.paths['/lot/{lotId}/history'].get").exists())
                .andExpect(jsonPath("$.paths['/wf'].post").exists())
                .andExpect(jsonPath("$.paths['/durable'].post").exists())
                .andExpect(jsonPath("$.paths['/hub/ingest'].post").exists())
                // 에러 응답 문서화 확인
                .andExpect(jsonPath("$.paths['/lot'].post.responses['400']").exists())
                .andExpect(jsonPath("$.paths['/lot'].post.responses['501']").exists())
                .andExpect(jsonPath("$.paths['/lot/{lotId}'].get.responses['404']").exists());
    }

    @Test
    void swaggerUi_isServed() throws Exception {
        this.mockMvc.perform(get("/swagger-ui/index.html"))
                .andExpect(status().isOk());
    }
}
